/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Item66Example */

#ifndef _Included_Item66Example
#define _Included_Item66Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Item66Example
 * Method:    print
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Item66Example_print
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif